# Generated by Django 3.0.7 on 2020-07-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extras_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FullTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_type_name', models.CharField(max_length=100)),
                ('number_of_extras', models.IntegerField()),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Types')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_price', models.FloatField()),
                ('extras_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Extras')),
                ('fulltype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.FullTypes')),
            ],
        ),
        migrations.CreateModel(
            name='BasePrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('fulltype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.FullTypes')),
                ('size_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Sizes')),
            ],
        ),
    ]
