# Generated by Django 3.0.7 on 2020-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200805_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.CharField(default='no session', max_length=100),
            preserve_default=False,
        ),
    ]
