# Generated by Django 3.0.7 on 2020-08-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session',
            field=models.CharField(max_length=100),
        ),
    ]
