# Generated by Django 3.0.7 on 2020-08-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200826_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.IntegerField(choices=[(1, 'Pick up in a restaurant')], default=1),
        ),
    ]
