# Generated by Django 3.0.7 on 2020-08-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200826_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryType',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
